## Settings
title: pRoJEct-ZeXIv
owner: "DeerRIDER"
# url: "akiritsu.github.io"
baseurl: ""
# baseurl: "/pRoJEct-ZeXIv"
permalink: /:title/
description: ""
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: "akiritsu@outlook.com"
github: "akiritsu/pRoJEct-NeGYa"
# path to: css/, fonts/, img/ and js/
toc_level: 3